[package]
name = "lipa"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "lp"
path = "src/main.rs"

[dependencies]
argon2 = "0.5.3"
clap = { version = "4.5.38", features = ["derive"] }
serde = "1.0.219"
